### ISSUE TITLE
La compilación de Travis falla

### ISSUE THREAD

**Issue by rmaceissoft** [manolo-rocks/django-manolo#164]
**Problema:**
La compilación de travis falla por los siguientes motivos:

1. Al ejecutar `pip install -r requirements/local.txt` ocurre el siguiente error:
```
ERROR: Cannot install -r requirements/base.txt (line 11), -r requirements/base.txt (line 13), -r requirements/base.txt (line 14), -r requirements/testing.txt (line 4) and Django==3.1.1 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested Django==3.1.1
    django-bootstrap-themes 3.3.6 depends on django>=1.4
    django-model-utils 2.2 depends on Django>=1.4.2
    djangorestframework 3.11.0 depends on django>=1.11
    model-mommy 1.2.2 depends on Django<1.8

```

2. La prueba unitaria `api.tests.test_api.TestAPI.test_search_return_json_with_pagination` falla con el siguiente error:

```
======================================================================
FAIL: test_search_return_json_with_pagination (api.tests.test_api.TestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/api/tests/test_api.py", line 31, in test_search_return_json_with_pagination
    c = self.client.get("/api/search.json/romulo/?page=2")
AssertionError: 200 != 404
```

**Solución:**

1. Actualizar la version de `model-mommy` para que sea compatible con `Django==3.1.1`
2. El campo `full_search` debe ser inicializado manualmente ya que `bulk_create` no invoca el método `save`

**Observaciones**
model-mommy ya no es mantenido y ha sido remplazado por model-bakery (https://pypi.org/project/model-bakery/). Se recomienda su remplazo

**Comment by aniversarioperu** [comment]
gracias! creo que este issue ya se corrigió con el merge? github ha cambiado y me confunde un poco.

**Comment by rmaceissoft** [comment]
yup!
