### ISSUE TITLE
Agregar Google Analytics

### ISSUE THREAD

**Issue by matiskay** [manolo-rocks/django-manolo#17]
Actualmente el sitio no cuenta con Google Analytics seria bueno usar Google Analytics para ver el uso de la plataforma asi como usar Google Analytics events registrar los clicks en los botones de submit.

* Js Layout en Manolo https://github.com/aniversarioperu/django-manolo/blob/78c4f96a4655054fbb27c9b0c434d86056829c91/manolo/templates/layout/js.html
* Google Analytics Events https://developers.google.com/analytics/devguides/collection/analyticsjs/events

**Comment by aniversarioperu** [comment]
manya está chevere eso.
