### ISSUE TITLE
Question out of interest

### ISSUE THREAD

**Issue by MichaelRueegg** [manolo-rocks/django-manolo#43]
Hi,

I'm also using Scrapinghub and wanted to ask you how your architecture looks like. I have Scrapy spiders on Scrapinghub, but I'm not sure how to best index the scraped data with ElasticSearch as there doesn't seam to be a possibility to use ElasticSearch on Scrapinghub. 

Do you have ElasticSearch somewhere else (e.g., Heroku)? How do you sync the data from Scrapinghub to your ElasticSearch instace? Do you regularly poll the Scrapinghub REST API and put all data into your Elasticsearch instance?

Thanks in advance,
Michael

**Comment by aniversarioperu** [comment]
hi Michael,

Scrapinghub now supports "Datasets" in which you can make publicly available the scraped items. For example see one of the Manolo runs here: https://app.scrapinghub.com/datasets/SPikMfKJrfl

In your server running the Manolo GUI, you could set up a cronjob to pull the full JSON file from Scrapinghub's Datasets and write the items into your local database (this could be done weekly). You can also setup another cronjob to update the elasticsearch index weekly.

The Scrapinghub's Datasets is a new service so I haven't fully integrated this into Manolo. Currently all Manolo's spiders are run in the same server that has the GUI. The spiders run weekly  (using this [bash script](https://github.com/manolo-rocks/manolo_scraper/blob/master/run_scraper.sh)) and the scraped items are uploaded to the local PostgreSQL database. Then the elasticsearch index is updated weekly. Our elasticsearch is in the very same server.

Writing the scraped items into the database is done by the spider itself. We have a pipeline that checks that scraped items are not in the database already. If the item is new, it will be saved into the database. See the pipeline function doing this: https://github.com/manolo-rocks/manolo_scraper/blob/master/manolo_scraper/manolo_scraper/pipelines.py#L66

**Comment by MichaelRueegg** [comment]
Hi @aniversarioperu,
Thanks a lot for your detailed explanations! They will help me much to get started with Scrapinghub.
