### ISSUE TITLE
implementar django native full text

### ISSUE THREAD

**Issue by aniversarioperu** [manolo-rocks/django-manolo#79]
https://docs.djangoproject.com/en/3.1/ref/contrib/postgres/search/

**Comment by aniversarioperu** [comment]
http://rubyjacket.com/build/django-psql-fts.html

**Comment by aniversarioperu** [comment]
actualemente estamos usando raw SQL para hacer la busqueda en la base de datos usando ts_vectors
<img width="659" alt="Screen Shot 2020-09-26 at 11 15 50" src="https://user-images.githubusercontent.com/5254076/94345205-d9842380-ffe9-11ea-97cf-80fe8787f7de.png">

Seria mejor si usamos el django ORM para hacer la busqueda. Por ahora solo hacemos busqueda de resultados en los campos full_name y id_document (nombre completo de visitante y numero de dni de visitante).

En la migration 0009 se creo una columna que agrupa a estos dos fields `full_name_dni` y un GIN indice para esta columna.

Otros issues veran cosas adicionales como ordenar los resultados por fecha e incluir campos adicionales como (nombre de persona que recibe la visita).

**Comment by manubellido** [comment]
FYI:

En #95 removí la dependencia de haystack y reemplacé la búsqueda con un simple 'objects.filter'. Suficiente para arreglar los tests.
