### ISSUE TITLE
corregir links rotos en search results

### ISSUE THREAD

**Issue by aniversarioperu** [manolo-rocks/django-manolo#89]
ninguno de los links funciona. Usuario debe poder hacer click en cualquier item y deberiamos devolver una lista de resultados luego de buscar el texto en la base de datos.
<img width="1228" alt="Screen Shot 2020-09-26 at 09 19 34" src="https://user-images.githubusercontent.com/5254076/94342850-a5a10200-ffd9-11ea-9f43-a71036ff4852.png">

**Comment by aniversarioperu** [comment]
por ahora es necesario que funcionen los links de las columnas `Visitante` y `Documento`. Por ahora hay que remover los links de las otras columnas.

**Comment by josemvaldivia** [comment]
Visitante y documento estan disponibles con #102

**Comment by josemvaldivia** [comment]
(no vi que habia este issue y lo habia hecho ahi simplemente por andar de boyscout)
